version: '3.8'
services:

  example-svc:
    image: 'bankbuddy.azurecr.io/boilerplate:v1'
    container_name: 'example-svc'
    build: .
    env_file:
      - config.env
    volumes:
      - .:/backend
    networks:
      - net

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - net

  postgres_console:
    image: 'postgres:13.4'
    container_name: 'postgres'
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=console
      - POSTGRES_PASSWORD=buddy123
      - POSTGRES_USER=consoleuser
    volumes:
      - ~/Desktop/pgdata:/var/lib/postgresql/data
    networks:
      - net


  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
    environment:
      MINIO_ROOT_USER: buddy
      MINIO_ROOT_PASSWORD: buddy123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}); do echo 'Waiting for MinIO...'; sleep 3; done;
      /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME};
      /usr/bin/mc policy set public myminio/${MINIO_BUCKET_NAME};
      "

volumes:
  minio_data:
