podTemplate(yaml: '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label-dynamic: "true"
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
      - /bin/sh
      - -c
      - sleep 3600
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      emptyDir: {}
'''
) {
    node(POD_LABEL) {
        container('kaniko') {
            stage('Checkout And Build Image') {
                checkout scm

                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh '''
                        mkdir -p /kaniko/.docker
                        cat > /kaniko/.docker/config.json <<EOF
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "$(echo -n "${USERNAME}:${PASSWORD}" | base64 -w 0)"
    }
  }
}
EOF
                    '''
                }

                sh '''
                    /kaniko/executor \
                      --context=${WORKSPACE} \
                      --dockerfile=${WORKSPACE}/Dockerfile \
                      --destination=nishanthveeru/jenkins-demo:${BUILD_NUMBER} \
                      --cache=true \
                      --cache-repo=nishanthveeru/jenkins-demo-cache
                '''
            }
        }
    }
}