podTemplate(yaml: '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label-dynamic: "true"
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
      - /bin/sh
      - -c
      - sleep 3600
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
    - name: git
      image: alpine/git:latest
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
  volumes:
    - name: docker-config
      emptyDir: {}
'''
) {
    node(POD_LABEL) {
        container('kaniko') {
            stage('Checkout And Build Image') {
                checkout scm

                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {
                    sh '''
                        mkdir -p /kaniko/.docker
                        cat > /kaniko/.docker/config.json <<EOF
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "$(echo -n "${USERNAME}:${PASSWORD}" | base64 -w 0)"
    }
  }
}
EOF
                    '''
                }

                sh '''
                    /kaniko/executor \
                      --context=${WORKSPACE} \
                      --dockerfile=${WORKSPACE}/Dockerfile \
                      --destination=nishanthveeru/jenkins-demo:${BUILD_NUMBER} \
                      --cache=true \
                      --cache-repo=nishanthveeru/jenkins-demo-cache
                '''
            }
        }
        
        container('git') {
            stage('Clone Repo and Update YAML') {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_TOKEN'
                )]) {
                    sh '''
                        git clone --branch test-jenkins --single-branch https://github.com/nishanth-affinsys/nishanth.git repo
                        cd repo
                        git config user.name "nishanth-affinsys"
                        git config user.email "nishanth.hg@affinsys.com"
                        
                        ./update.sh ./pod.yaml ${BUILD_NUMBER}
                        
                        git add .
                        git commit -m "artifact update: ${BUILD_NUMBER}"
                        git push https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/nishanth-affinsys/nishanth.git test-jenkins
                    '''
                }
            }
        }
    }
}