# Generated by Django 3.2.2 on 2023-06-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AbondanedDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("session", models.CharField(blank=True, max_length=36, null=True)),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("social_id", models.BigIntegerField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("event", models.CharField(blank=True, max_length=200, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "abondaned_details",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AgentLastActivityTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateField(blank=True, null=True)),
                ("diff", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=199, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "agent_last_activity_time",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AgentProductivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "agent_routed",
                    models.TextField(blank=True, db_column="Agent Routed", null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=36, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "agent_accept",
                    models.TextField(blank=True, db_column="Agent Accept", null=True),
                ),
                (
                    "accept_time",
                    models.DurationField(
                        blank=True, db_column="Accept Time", null=True
                    ),
                ),
                (
                    "initial_time",
                    models.DateTimeField(
                        blank=True, db_column="Initial Time", null=True
                    ),
                ),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "agent_productivity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.BigIntegerField(blank=True, null=True)),
                ("skill_id", models.BigIntegerField(blank=True, null=True)),
                ("skill_name", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(blank=True, max_length=199, null=True)),
                ("tenant", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "agent_skill",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AgentTiming",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("working_day", models.CharField(max_length=1, unique=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "db_table": "agent_timing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AgentTransfer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "parent_session_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("transferred_agents", models.TextField(blank=True, null=True)),
                ("initial_agent", models.TextField(blank=True, null=True)),
                ("total_session", models.DurationField(blank=True, null=True)),
                ("initial_time", models.DateTimeField(blank=True, null=True)),
                ("accept_time", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "agent_transfer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CurrentLoggedIn",
            fields=[
                ("agent_id", models.BigIntegerField(blank=True, null=True)),
                ("skill_name", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(blank=True, max_length=199, null=True)),
                ("is_online", models.BooleanField(blank=True, null=True)),
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("tenant", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "current_logged_in",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Handoffduration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=199, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("session", models.CharField(blank=True, max_length=36, null=True)),
                ("minutes", models.FloatField(blank=True, null=True)),
                ("agent_id", models.BigIntegerField(blank=True, null=True)),
                ("social_id", models.BigIntegerField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "handoffduration",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HandoffFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=36, null=True)),
                ("source", models.CharField(blank=True, max_length=200, null=True)),
                ("target", models.CharField(blank=True, max_length=200, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "handoff_flow",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NewUserInHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("channel_id", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "new_user_in_handoff",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ReturningUserInHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
                ("return_time", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("channel_id", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "returning_user_in_handoff",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationAgent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=199, unique=True)),
                ("max_concurrent", models.IntegerField()),
                ("current_chats", models.IntegerField()),
                ("is_online", models.BooleanField()),
                ("is_ready", models.BooleanField()),
                ("username", models.CharField(max_length=199)),
            ],
            options={
                "db_table": "socialconversation_agent",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationAttributes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("attribute_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "socialconversation_attributes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationCannedresponses",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=50, unique=True)),
                ("text", models.CharField(max_length=499)),
            ],
            options={
                "db_table": "socialconversation_cannedresponses",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationSentiment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sentiment_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "socialconversation_sentiment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationSkill",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("skill_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "socialconversation_skill",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationSocialplatformmixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "socialconversation_socialplatformmixin",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationTag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "socialconversation_tag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationTempsocialuser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200)),
                ("channel_id", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("channel", models.CharField(blank=True, max_length=50, null=True)),
                ("skill", models.CharField(blank=True, max_length=200, null=True)),
                ("last_activity", models.DateTimeField()),
                ("is_circulating", models.BooleanField()),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_tempsocialuser",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationTenant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "socialconversation_tenant",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationDirectMessage",
            fields=[
                (
                    "socialplatformmixin_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="handoff.socialconversationsocialplatformmixin",
                    ),
                ),
                ("body", models.CharField(blank=True, max_length=100, null=True)),
                ("sentiment", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=50)),
                ("sender", models.CharField(max_length=255)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="receiver",
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user",
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_direct_message",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationTempsocialuserattribute",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationattributes",
                    ),
                ),
                (
                    "social_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_tempsocialuserattribute",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationTagsocialmessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "social_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationsocialplatformmixin",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtag",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_tagsocialmessage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationAgenttenant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtenant",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_agenttenant",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationAgentskill",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationskill",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_agentskill",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationAgentsecondaryskill",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationskill",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_agentsecondaryskill",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChatSocialagentsession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "chat_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
                (
                    "social_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
            ],
            options={
                "db_table": "chat_socialagentsession",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AuditlogLogentry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_pk", models.CharField(max_length=255)),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                ("object_repr", models.TextField()),
                ("action", models.SmallIntegerField()),
                ("changes", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("additional_data", models.JSONField(blank=True, null=True)),
                ("serialized_data", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.authuser",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.djangocontenttype",
                    ),
                ),
            ],
            options={
                "db_table": "auditlog_logentry",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSocialevent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=200)),
                ("event", models.CharField(max_length=200)),
                ("session", models.CharField(max_length=36)),
                ("timestamp", models.DateTimeField()),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("supervisor", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bot_session_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("parent_session_id", models.CharField(max_length=36)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
                (
                    "social",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_socialevent",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationSocialusernotes",
            fields=[
                (
                    "socialplatformmixin_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="handoff.socialconversationsocialplatformmixin",
                    ),
                ),
                ("note", models.CharField(max_length=150)),
                (
                    "social_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_socialusernotes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SocialconversationSentimentrelation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sentiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationsentiment",
                    ),
                ),
                (
                    "direct_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationdirectmessage",
                    ),
                ),
            ],
            options={
                "db_table": "socialconversation_sentimentrelation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChatMessagesocialagent",
            fields=[
                (
                    "socialplatformmixin_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="handoff.socialconversationsocialplatformmixin",
                    ),
                ),
                ("sender", models.CharField(max_length=13)),
                ("body", models.TextField()),
                ("sentiment", models.CharField(max_length=100)),
                ("message_type", models.CharField(max_length=100)),
                ("intent", models.CharField(blank=True, max_length=200, null=True)),
                ("session_key", models.CharField(blank=True, max_length=36, null=True)),
                ("tenant", models.CharField(blank=True, max_length=201, null=True)),
                (
                    "chat_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationagent",
                    ),
                ),
                (
                    "social_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="handoff.socialconversationtempsocialuser",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messagesocialagent",
                "managed": True,
            },
        ),
    ]
