# Generated by Django 4.2.5 on 2023-12-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(blank=True, max_length=100, null=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("operation", models.CharField(blank=True, max_length=100, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=200, null=True)),
                ("result", models.CharField(blank=True, max_length=100, null=True)),
                ("status_code", models.CharField(blank=True, max_length=10, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status_code_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("request_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("execution_time", models.CharField(max_length=50)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "activity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ApiLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("endpoint", models.CharField(blank=True, max_length=200, null=True)),
                ("channel_id", models.CharField(blank=True, max_length=150, null=True)),
                ("request_id", models.CharField(blank=True, max_length=150, null=True)),
                ("session_id", models.CharField(blank=True, max_length=50, null=True)),
                ("api", models.CharField(blank=True, max_length=500, null=True)),
                ("stage", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(blank=True, max_length=500, null=True)),
                ("channel", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("data", models.TextField(blank=True, null=True)),
                ("exception", models.CharField(blank=True, max_length=500, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "api_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignNotification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("campaign_variants", models.BigIntegerField(blank=True, null=True)),
                (
                    "campaign_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "campaign_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "sub_campaign_identifier",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "sub_campaign_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("run_id", models.IntegerField(blank=True, null=True)),
                ("created_timestamp", models.DateTimeField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(blank=True, null=True)),
                ("batch_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "batch_identifier",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("message_id", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "notification_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notification_timestamp", models.DateTimeField(blank=True, null=True)),
                ("notification_exceptions", models.TextField(blank=True, null=True)),
                ("profile_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("channel_id", models.CharField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("message_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "campaign_notification",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignRolled",
            fields=[
                (
                    "message_row_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("channel_id", models.CharField(blank=True, max_length=150, null=True)),
                ("channel", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "batch_identifier",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "campaign_rolled",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChannelReaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("page_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "action_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=100, null=True)),
                ("post_id", models.CharField(blank=True, max_length=100, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "channel_reaction",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ComplaintTicketLogs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("srn", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("last_updated_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.CharField(blank=True, max_length=10, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=100, null=True)),
                ("hold_time", models.BigIntegerField(blank=True, null=True)),
                ("created_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "breached_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "complaint_ticket_logs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LatestRegistrationActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("registered", models.CharField(blank=True, max_length=50, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "latest_registration_activity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LlmProject",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100, unique=True)),
                ("collection", models.CharField(max_length=100, unique=True)),
                ("directory", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "llm_project",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=50)),
                ("session_id", models.CharField(blank=True, max_length=50, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=20, null=True)),
                ("context", models.CharField(blank=True, max_length=50, null=True)),
                ("handled", models.CharField(blank=True, max_length=1, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("intent", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=30, null=True
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=50, null=True)),
                ("event_type", models.CharField(blank=True, max_length=50, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "message_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=150)),
                ("message_id", models.CharField(blank=True, max_length=100, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "message_status",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NetRegistrationActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "net_registration_activity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RecentTicketActivity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("srn", models.CharField(blank=True, max_length=50, null=True)),
                ("last_updated_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.CharField(blank=True, max_length=10, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=100, null=True)),
                ("hold_time", models.BigIntegerField(blank=True, null=True)),
                ("created_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "breached_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "recent_ticket_activity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("service", models.CharField(max_length=100)),
                ("healthz_endpoint", models.CharField(max_length=200)),
                ("healthz_status", models.CharField(max_length=50)),
                ("livez_endpoint", models.CharField(max_length=200)),
                ("livez_status", models.CharField(max_length=50)),
                ("created_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "last_modified_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "service_status",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=50)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                ("session_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "transaction_intent",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("stage", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "stage_result",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("rmn", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "transaction_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("node_id", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "stage_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StageLogAuth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(blank=True, max_length=40, null=True)),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                ("result", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "result_detail",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("ip_info", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "stage_log_auth",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SunshineMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "conversation_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "sunshine_mapping",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(blank=True, max_length=150, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("target", models.TextField(blank=True, null=True)),
                ("channel", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                ("rank", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_flow",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="console.activity",
                    ),
                ),
                ("request_body", models.TextField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "activity_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LlmWebsite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("website", models.CharField(max_length=200)),
                ("indexing_status", models.CharField(max_length=10)),
                ("vector_ids", models.JSONField()),
                ("user_id", models.CharField(max_length=100)),
                ("last_updated_at", models.DateTimeField()),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="console.llmproject",
                    ),
                ),
            ],
            options={
                "db_table": "llm_website",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LlmDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=100)),
                ("object_path", models.CharField(max_length=100)),
                ("bucket_name", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                ("last_updated_at", models.DateTimeField()),
                ("indexing_status", models.CharField(max_length=10)),
                ("vector_ids", models.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="console.llmproject",
                    ),
                ),
            ],
            options={
                "db_table": "llm_document",
                "managed": True,
            },
        ),
    ]
