sonar.projectKey=bud-core-Analytics-svc
sonar.exclusions= **/venv/**,**/tests/**,**apps.py,**manage.py,**/migrations/**,**asgi.py,**wsgi.py,**urls.py,**settings.py,**celery.py,**/locust/**,devops/**
sonar.coverage.exclusions= **/venv/**,**/tests/**,**apps.py,**manage.py,**/migrations/**,**asgi.py,**wsgi.py,**urls.py,**settings.py,**celery.py,**/locust/**,devops/**
sonar.python.coverage.reportPaths= coverage.xml
sonar.python.version= 3
sonar.sources= . 
sonar.duplications=blocks