apiVersion: v1
kind: Service
metadata:
  name: buildkit
  namespace: buildkit
spec:
  selector:
    app: buildkit
  ports:
  - port: 1234
    targetPort: 1234
    protocol: TCP
    name: buildkit
  type: ClusterIP
