# Generated by Django 4.2.5 on 2023-10-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_modified", models.DateTimeField()),
                ("campaign_id", models.TextField()),
                ("parent", models.CharField(max_length=50)),
                ("campaign_name", models.CharField(max_length=100)),
                ("campaign_type", models.CharField(max_length=50)),
                ("campaign_description", models.CharField(max_length=100)),
                ("campaign_tags", models.TextField(blank=True, null=True)),
                ("tenant", models.CharField(max_length=50)),
                ("archived", models.BooleanField()),
                ("status", models.CharField(max_length=50)),
                ("created_timestamp", models.DateTimeField()),
                ("campaign_category", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "campaign",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCampaign",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "campaigns_campaign",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCampaignvariant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_variant", models.BooleanField()),
                ("status", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("archived", models.BooleanField()),
                ("timestamp", models.DateTimeField()),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_campaignvariant",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsChannelcontent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.JSONField()),
            ],
            options={
                "db_table": "campaigns_channelcontent",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCreativecontent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content_type", models.CharField(max_length=100)),
                ("channel", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                (
                    "campaign_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
                (
                    "channel_content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignschannelcontent",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_creativecontent",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "notification_batch",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NotificationRolled",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("channel_id", models.CharField(max_length=250)),
                ("channel_name", models.CharField(max_length=50)),
                ("service_name", models.CharField(max_length=50)),
                ("utter_name", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=500)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.notificationbatch",
                    ),
                ),
            ],
            options={
                "db_table": "notification_rolled",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileDataChanneldata",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(max_length=100)),
                ("is_opted", models.BooleanField()),
                ("is_subscribed", models.BooleanField()),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "profile_data_channeldata",
                "managed": True,
                "unique_together": {("channel_id", "channel_name", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="ProfileDataProfiledata",
            fields=[
                ("profile_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "external_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email_id", models.CharField(blank=True, max_length=100, null=True)),
                ("rmn", models.CharField(blank=True, max_length=25, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("created_timestamp", models.DateTimeField()),
                ("modified_timestamp", models.DateTimeField()),
                ("is_deprecated", models.BooleanField()),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "profile_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "profile_data_profiledata",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignContentSegment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cj_name", models.CharField(max_length=100)),
                ("channel_instance", models.CharField(max_length=100)),
                ("task_id", models.CharField(max_length=100)),
                ("cj_id", models.IntegerField(blank=True, null=True)),
                ("segment_name", models.CharField(max_length=100)),
                ("channels", models.TextField(blank=True, null=True)),
                ("language", models.CharField(max_length=100)),
                ("utter_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sub_campaign_content_segment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("identifier", models.CharField(max_length=50)),
                ("is_primary", models.BooleanField()),
                ("type", models.CharField(max_length=100)),
                ("created_timestamp", models.DateTimeField()),
                ("last_modified", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "sub_campaign_detail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("run_id", models.IntegerField()),
                ("notification_id", models.CharField(max_length=250)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaign",
                    ),
                ),
                (
                    "sub_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigndetail",
                    ),
                ),
            ],
            options={
                "db_table": "sub_campaign_run",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignTargetSegment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("csv_upload", models.BooleanField()),
                ("segment_name", models.CharField(max_length=100)),
                ("cj_name", models.CharField(max_length=100)),
                ("task_id", models.CharField(max_length=100)),
                ("cj_id", models.IntegerField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "sub_campaign_target_segment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileDataProfiledataOptedoutMarketing",
            fields=[
                ("attr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="campaign_manager.profiledataprofiledata",
                    ),
                ),
            ],
            options={
                "db_table": "profile_data_profiledata_optedout_marketing",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileDataProfiledataOptedoutUtility",
            fields=[
                ("attr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="campaign_manager.profiledataprofiledata",
                    ),
                ),
            ],
            options={
                "db_table": "profile_data_profiledata_optedout_utility",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileDataProfiledataSlotUuid",
            fields=[
                ("attr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="campaign_manager.profiledataprofiledata",
                    ),
                ),
            ],
            options={
                "db_table": "profile_data_profiledata_slot_uuid",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("segment_name", models.CharField(max_length=100)),
                ("profile_id", models.CharField(max_length=100)),
                ("channel", models.CharField(max_length=10)),
                (
                    "campaign_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaignrun",
                    ),
                ),
                (
                    "target_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigntargetsegment",
                    ),
                ),
            ],
            options={
                "db_table": "sub_campaign_user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignTarget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigncontentsegment",
                    ),
                ),
                (
                    "sub_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigndetail",
                    ),
                ),
                (
                    "target_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigntargetsegment",
                    ),
                ),
            ],
            options={
                "db_table": "sub_campaign_target",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignSegmentSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("interval", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                (
                    "sub_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigndetail",
                    ),
                ),
            ],
            options={
                "db_table": "sub_campaign_segment_schedule",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubCampaignContentSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=100)),
                ("event_end_type", models.CharField(max_length=100)),
                (
                    "event_end_value_occurence",
                    models.IntegerField(blank=True, null=True),
                ),
                ("event_end_value_time", models.DateTimeField(blank=True, null=True)),
                ("event_schedule", models.CharField(max_length=100)),
                ("repeat_interval", models.IntegerField(blank=True, null=True)),
                ("repeats_on", models.TextField(blank=True, null=True)),
                ("schedule_type", models.CharField(max_length=100)),
                ("interval", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(max_length=100)),
                (
                    "relativeto",
                    models.ForeignKey(
                        blank=True,
                        db_column="relativeTo_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subcampaigncontentschedule_relativeto_set",
                        to="campaign_manager.subcampaigndetail",
                    ),
                ),
                (
                    "sub_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigndetail",
                    ),
                ),
            ],
            options={
                "db_table": "sub_campaign_content_schedule",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProfileDataProfilechannel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "channel_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.profiledatachanneldata",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.profiledataprofiledata",
                    ),
                ),
            ],
            options={
                "db_table": "profile_data_profilechannel",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("message_id", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.notificationrolled",
                    ),
                ),
            ],
            options={
                "db_table": "notification_status",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignUserLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("segment_name", models.CharField(max_length=100)),
                ("profile_id", models.CharField(max_length=100)),
                ("group_id", models.UUIDField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaign",
                    ),
                ),
                (
                    "subcampaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.subcampaigndetail",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_user_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsPushbroadcasttimeline",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("frequency", models.IntegerField()),
                ("recurrence_interval", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("completed_count", models.IntegerField()),
                ("last_timestamp", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField()),
                (
                    "campaign_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_pushbroadcasttimeline",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsPullbroadcasttimeline",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("is_active", models.BooleanField()),
                ("end_date", models.DateTimeField()),
                (
                    "campaign_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_pullbroadcasttimeline",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCreativecontentlocation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                (
                    "creative_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscreativecontent",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_creativecontentlocation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCampaignvariantusers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                (
                    "campaign_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_campaignvariantusers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCampaignvariantdetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_recommended_cohorts", models.JSONField()),
                ("product_product_filters", models.JSONField()),
                ("product_cohorts_filter", models.JSONField()),
                ("product_product_list", models.JSONField()),
                ("product_selected_products", models.JSONField()),
                ("user_product_filters", models.JSONField()),
                ("user_recommended_products", models.JSONField()),
                ("user_selected_cohorts", models.JSONField()),
                ("user_user_cohorts", models.JSONField()),
                ("user_user_filters", models.JSONField()),
                ("selected_users", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                ("user_selected_products", models.JSONField()),
                (
                    "campaign_variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_campaignvariantdetail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsCampaignvariantapproval",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("approval_status", models.CharField(max_length=100)),
                (
                    "campaign_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_campaignvariantapproval",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsBroadcastusermessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("message_id", models.CharField(blank=True, max_length=100, null=True)),
                ("channel", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "campaign_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_broadcastusermessage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsBroadcastreport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("customer", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                (
                    "creative_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscreativecontent",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_broadcastreport",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsApprovalcomment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                (
                    "approval_obj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignscampaignvariantapproval",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_approvalcomment",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsPushbroadcastreport",
            fields=[
                (
                    "broadcastreport_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="campaign_manager.campaignsbroadcastreport",
                    ),
                ),
                ("channel", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
                ("message_id", models.CharField(max_length=255)),
                ("initialized", models.DateTimeField()),
                ("sent", models.DateTimeField(blank=True, null=True)),
                ("read", models.DateTimeField(blank=True, null=True)),
                ("delivered", models.DateTimeField(blank=True, null=True)),
                ("clicked", models.DateTimeField(blank=True, null=True)),
                (
                    "push_broadcast_timeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignspushbroadcasttimeline",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_pushbroadcastreport",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CampaignsPullbroadcastreport",
            fields=[
                (
                    "broadcastreport_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="campaign_manager.campaignsbroadcastreport",
                    ),
                ),
                (
                    "pull_broadcast_timeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="campaign_manager.campaignspullbroadcasttimeline",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_pullbroadcastreport",
                "managed": True,
            },
        ),
    ]
