from auth.tags import AuthTags
from drf_spectacular.utils import extend_schema

from console.services.reg_deregistration_utils import (
    net_registration_activity_generic,
    number_of_registrations_bigno_generic,
    number_of_registrations_list_generic,
)

from rest_framework.decorators import action
from rest_framework.viewsets import GenericViewSet

from main.settings import MAX_PDF_LIMIT
from main.utils.export import export_csv, export_pdf
from main.utils.boiler_plate import return_table, return_count


class RegDeregViewSet(GenericViewSet):  # For ApiLog Report
    @extend_schema(
        operation_id="bot_net_registration_activity",
        tags=[AuthTags.AUTHORIZE],
        description="Used for displaying Number of registrations and de-registrations happened at the end of the day",
    )
    @action(methods=["POST"], detail=False, url_path="bot_net_registration_activity")
    def net_registration_activity(self, request, *args, **kwargs):
        """
        The net_registration_activity function returns a table of the net registration activity for each day in the specified time range.

        :param self: Represent the instance of the class
        :param request: Get the data from the request object
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: A table with the following columns:
        """
        items, _, _ = net_registration_activity_generic(request)
        return return_table(items, request)

    @extend_schema(
        operation_id="bot_net_registration_activity_export_csv",
        tags=[AuthTags.AUTHORIZE],
        description="Used for Download Number of registrations and de-registrations happened at the end of the day",
    )
    @action(
        methods=["POST"],
        detail=False,
        url_path="bot_net_registration_activity_export_csv",
    )
    def net_registration_activity_export(self, request, *args, **kwargs):
        """
        The net_registration_activity_export function is a custom function that allows the user to export
        a CSV file containing the net registration activity for a given time period. The data in this CSV file
        is generated by querying the NetRegistrationActivity table in our event database, and then filtering
        the results based on date range parameters provided by the user. The resulting data is then exported as
        a CSV file.

        :param self: Represent the instance of the class
        :param request: Get the data from the request object
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A csv file with the following columns:
        """
        response, field_names, file_name = net_registration_activity_generic(request)
        items = export_csv(
            response,
            field_names,
            f"{file_name}.csv",
        )
        return items

    # pdf for net registration activities
    @extend_schema(
        operation_id="bot_net_registration_activity_export_pdf",
        tags=[AuthTags.AUTHORIZE],
        description="Used for Download Number of registrations and de-registrations happened at the end of the day",
    )
    @action(
        methods=["POST"],
        detail=False,
        url_path="bot_net_registration_activity_export_pdf",
    )
    def net_registration_activity_export_pdf(self, request, *args, **kwargs):
        """
        The net_registration_activity_export_pdf function is used to export the net registration activity data as a PDF file.
        The function takes in the request and kwargs, which are then added to filter_data. The items variable is set equal to
        the NetRegistrationActivity objects that have been filtered by date, tenant name, and action (register or deregister).
        If there are more than MAX_PDF_LIMIT items in the list of NetRegistrationActivity objects, only MAX_PDF_LIMIT will be exported. The function
        then returns an export_pdf object with parameters: items (list of NetRegistrationActivity objects), column names for each item
        in the list (&quot;Date&quot;,

        :param self: Represent the instance of the class
        :param request: Get the data from the request object
        :param *args: Catch any extra arguments that are passed to the function
        :param **kwargs: Pass a variable number of keyword arguments to a function
        :return: A pdf file
        """
        response, field_names, file_name = net_registration_activity_generic(request)
        if len(response) > MAX_PDF_LIMIT:
            response = response[:MAX_PDF_LIMIT]
        items = export_pdf(
            response,
            field_names,
            f"{file_name}.pdf",
            "Net Registration Activities",
            request.user.username,
        )
        return items

    @extend_schema(
        operation_id="bot_number_of_registrations_bigno",
        tags=[AuthTags.AUTHORIZE],
        description="Used for display the Number of registered current users ",
    )
    @action(
        methods=["POST"], detail=False, url_path="bot_number_of_registrations_bigno"
    )
    def number_of_registrations_bigno(self, request, *args, **kwargs):
        """
        The number_of_registrations_bigNo function returns the number of registrations for a given event.

        :param self: Represent the instance of the object itself
        :param request: Get the data from the request
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: The number of registrations
        """
        items = number_of_registrations_bigno_generic(request, True)
        return return_count(items)

    @extend_schema(
        operation_id="bot_number_of_deregistrations_bigno",
        tags=[AuthTags.AUTHORIZE],
        description="Used for display the Number of deregistered current users ",
    )
    @action(
        methods=["POST"], detail=False, url_path="bot_number_of_deregistrations_bigno"
    )
    def number_of_deregistrations_bigno(self, request, *args, **kwargs):
        """
        The number_of_deregistrations_bigNo function returns the number of deregistrations for a given event.

        :param self: Represent the instance of the object itself
        :param request: Get the data from the request object
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: The number of deregistrations
        """
        items = number_of_registrations_bigno_generic(request, False)
        return return_count(items)

    @extend_schema(
        operation_id="bot_number_of_registrations_list",
        tags=[AuthTags.AUTHORIZE],
        description="Used for display the list of registered current users ",
    )
    @action(methods=["POST"], detail=False, url_path="bot_number_of_registrations_list")
    def number_of_registrations_list(self, request, *args, **kwargs):
        """
        The number_of_registrations_list function returns a list of all the mobile numbers that have registered for an event.
        The function takes in a request object and keyword arguments, which are used to filter the data returned by the function.
        The timezone is set to UTC+5:30 (India Standard Time) using pytz library. The items variable stores all the mobile numbers
        that have registered for an event along with their timestamps in seconds.

        :param self: Represent the instance of the object
        :param request: Get the data from the request object
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A list of mobile numbers and timestamps
        """
        items, _, _ = number_of_registrations_list_generic(request, True)
        return return_table(items, request)

    @extend_schema(
        operation_id="bot_number_of_registrations_list_export_csv",
        tags=[AuthTags.AUTHORIZE],
        description="Used for Download the list of registered current users ",
    )
    @action(
        methods=["POST"],
        detail=False,
        url_path="bot_number_of_registrations_list_export_csv",
    )
    def number_of_registrations_list_export(self, request, *args, **kwargs):
        """
        The number_of_registrations_list_export function is used to export the list of registrations for a particular event.
        The function takes in the request and kwargs as parameters, and returns an export_csv object that contains all of
        the registration data for a particular event.

        :param self: Represent the instance of the class
        :param request: Get the data from the request object
        :param *args: Pass a non-keyworded, variable-length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A csv file with the mobile numbers and timestamps of all registrations
        """
        response, field_names, file_name = number_of_registrations_list_generic(
            request, True
        )
        items = export_csv(response, field_names, f"{file_name}.csv")
        return items

    # pdf for registration list
    @extend_schema(
        operation_id="bot_number_of_registrations_list_export_pdf",
        tags=[AuthTags.AUTHORIZE],
        description="Used for Download the list of registered current users ",
    )
    @action(
        methods=["POST"],
        detail=False,
        url_path="bot_number_of_registrations_list_export_pdf",
    )
    def number_of_registrations_list_export_pdf(self, request, *args, **kwargs):
        """
        The number_of_registrations_list_export_pdf function is used to export the number of registrations list as a PDF file.
        The function takes in the request and kwargs parameters, which are then passed into filter_data. The timezone information is then retrieved from settings.TIME_ZONE and stored in tz_info.
        The items variable stores all of the latest registration activity data that has been filtered by tenant name, registered status, mobile number and timestamp (truncated to seconds). If there are more than MAX_PDF_LIMIT items returned by this query, only MAX_PDF_LIMIT will be displayed on screen.

        :param self: Represent the instance of the class
        :param request: Get the data from the request
        :param *args: Pass a non-keyworded, variable-length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A pdf file
        """
        response, field_names, file_name = number_of_registrations_list_generic(
            request, True
        )
        if len(response) > MAX_PDF_LIMIT:
            response = response[:MAX_PDF_LIMIT]
        items = export_pdf(
            response,
            field_names,
            f"{file_name}.pdf",
            "Registration List",
            request.user.username,
        )
        return items

    @extend_schema(
        operation_id="bot_number_of_deregistrations_list",
        tags=[AuthTags.AUTHORIZE],
        description="Used for display the list of deregistered current users ",
    )
    @action(
        methods=["POST"], detail=False, url_path="bot_number_of_deregistrations_list"
    )
    def number_of_deregistrations_list(self, request, *args, **kwargs):
        """
        The number_of_deregistrations_list function returns a list of all the deregistrations that have occurred in the system.
        The function takes in a request object and uses it to filter data based on parameters passed into it.
        It then queries the database for all instances of deregistration, and returns them as JSON objects.

        :param self: Represent the instance of the class
        :param request: Get the request data from the frontend
        :param *args: Send a non-keyworded variable length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list to a function
        :return: A list of mobile numbers and timestamps for each deregistration
        """
        items, _, _ = number_of_registrations_list_generic(request, False)
        return return_table(items, request)

    @extend_schema(
        operation_id="bot_number_of_deregistrations_list_export_csv",
        tags=[AuthTags.AUTHORIZE],
        description="Used for Download the list of deregistered current users ",
    )
    @action(
        methods=["POST"],
        detail=False,
        url_path="bot_number_of_deregistrations_list_export_csv",
    )
    def number_of_deregistrations_list_export(self, request, *args, **kwargs):
        """
        The number_of_deregistrations_list_export function is used to export a list of all the deregistrations that have occurred in the system.
        The function takes in a request object and returns an exported CSV file containing all of the deregistrations.

        :param self: Represent the instance of the class
        :param request: Get the data from the request object
        :param *args: Pass a non-keyworded, variable-length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A csv file with the mobile numbers and timestamps of all deregistrations
        """
        response, field_names, file_name = number_of_registrations_list_generic(
            request, False
        )
        items = export_csv(response, field_names, f"{file_name}.csv")
        return items

    @extend_schema(
        operation_id="bot_number_of_deregistrations_list_export_pdf",
        tags=[AuthTags.AUTHORIZE],
        description="Used for Download the list of deregistered current users ",
    )
    @action(
        methods=["POST"],
        detail=False,
        url_path="bot_number_of_deregistrations_list_export_pdf",
    )
    def number_of_deregistrations_list_export_pdf(self, request, *args, **kwargs):
        """
        The number_of_deregistrations_list_export_pdf function is used to export the number of deregistrations list as a PDF file.

        :param self: Represent the instance of the class
        :param request: Get the request object
        :param *args: Pass a non-keyworded, variable-length argument list to the function
        :param **kwargs: Pass keyworded, variable-length argument list
        :return: A pdf file
        """
        response, field_names, file_name = number_of_registrations_list_generic(
            request, False
        )
        if len(response) > MAX_PDF_LIMIT:
            response = response[:MAX_PDF_LIMIT]
        items = export_pdf(
            response,
            field_names,
            f"{file_name}.pdf",
            "Deregistration List",
            request.user.username,
        )
        return items
