# Generated by Django 4.2.5 on 2023-11-20 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetailedReportTableRt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "primary_contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "last_modified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("submit_by", models.CharField(blank=True, max_length=255, null=True)),
                ("submit_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "account_num1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_num2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "present_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("queue_name", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "onboarding_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_performed_by",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "detailed_report_table_rt",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DetailedReportTableSp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "primary_contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "last_modified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("submit_by", models.CharField(blank=True, max_length=255, null=True)),
                ("submit_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "account_num1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_num2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "present_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("queue_name", models.CharField(blank=True, max_length=100, null=True)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "onboarding_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_performed_by",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "detailed_report_table_sp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmailReceivers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("sm_sp", models.CharField(max_length=50)),
                ("agent", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "branch_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "email_receivers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FileReferenceManagementKyc",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField()),
                (
                    "screen_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("key_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bucket_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("obj_path", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "internal_file_name_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_file_name_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "uploaded_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uploaded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uploaded_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upload_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "file_reference_management_kyc",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FileReferenceManagementRt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField()),
                (
                    "screen_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("key_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bucket_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("obj_path", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "internal_file_name_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_file_name_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "uploaded_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uploaded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upload_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "file_reference_management_rt",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FileReferenceManagementSp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField()),
                (
                    "screen_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("key_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bucket_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("obj_path", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "internal_file_name_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_file_name_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("file_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "uploaded_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uploaded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upload_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "file_reference_management_sp",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="KycApplicationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_perform_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "kyc_application_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="KycAuditComments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "created_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                ("queue_code", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "action_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "kyc_audit_comments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="KycRoutingLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("route_dump", models.TextField(blank=True, null=True)),
                ("condition_dump", models.TextField(blank=True, null=True)),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perform_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "kyc_routing_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProcessMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("process_name", models.CharField(max_length=255)),
                ("process_list", models.TextField()),
            ],
            options={
                "db_table": "process_mapping",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QueueActionMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("queue_code", models.CharField(max_length=200)),
                ("queue_name", models.CharField(max_length=200)),
                ("action_code", models.CharField(max_length=200)),
                ("action_name", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "queue_action_mapping",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RoutingRules",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "route_condition_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("route_condition", models.TextField()),
            ],
            options={
                "db_table": "routing_rules",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RtApiStage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("completion_status", models.CharField(max_length=1)),
                ("pending_functions", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "rt_api_stage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RtApplicationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "action_perform_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "rt_application_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RtAuditComments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "created_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                ("queue_code", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "action_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "branch_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "rt_audit_comments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RtRoutingLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("route_dump", models.TextField(blank=True, null=True)),
                ("condition_dump", models.TextField(blank=True, null=True)),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perform_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "rt_routing_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpApiStage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("completion_status", models.CharField(max_length=1)),
                ("pending_functions", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sp_api_stage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpApplicationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("event_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "action_perform_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sp_application_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpAuditComments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "created_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                ("queue_code", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "action_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "branch_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sp_audit_comments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SpRoutingLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                ("route_dump", models.TextField(blank=True, null=True)),
                ("condition_dump", models.TextField(blank=True, null=True)),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perform_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sp_routing_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserRoleConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("user_uuid", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=200)),
                ("role_name", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "user_role_config",
                "managed": True,
                "unique_together": {
                    ("tenant", "user_uuid", "username", "provider", "role", "role_name")
                },
            },
        ),
        migrations.CreateModel(
            name="UserBranchConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("branch_code", models.CharField(max_length=50)),
                ("branch_type", models.CharField(max_length=50)),
                ("branch_name", models.CharField(max_length=255)),
                ("user_uuid", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("is_deleted", models.CharField(max_length=1)),
            ],
            options={
                "db_table": "user_branch_config",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "user_uuid",
                        "username",
                        "provider",
                        "email",
                        "branch_code",
                        "branch_type",
                        "branch_name",
                        "is_deleted",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="SpProductMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("product_key", models.CharField(max_length=50, unique=True)),
                ("product_name", models.CharField(max_length=50)),
                ("product_icon_path", models.TextField(blank=True, null=True)),
                (
                    "product_channel",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("scheme_description", models.TextField(blank=True, null=True)),
                ("documents_required", models.TextField(blank=True, null=True)),
                ("key_fact_path", models.TextField(blank=True, null=True)),
                ("account_type", models.CharField(max_length=50)),
                (
                    "applicable_gender",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("scheme_code", models.CharField(max_length=50)),
                ("scheme_type", models.CharField(max_length=50)),
                ("gl_subhead_code", models.CharField(max_length=75)),
                (
                    "customer_nationality",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("account_currency", models.CharField(max_length=50)),
                (
                    "account_turnover",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("process_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "sp_product_mapping",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "product_key",
                        "product_name",
                        "product_channel",
                        "account_type",
                        "applicable_gender",
                        "scheme_code",
                        "scheme_type",
                        "gl_subhead_code",
                        "customer_nationality",
                        "account_currency",
                        "account_turnover",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="SingleCifSpDataHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "internal_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("archive_data", models.TextField(blank=True, null=True)),
                (
                    "archived_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "archived_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "single_cif_sp_data_history",
                "managed": True,
                "unique_together": {("internal_reference", "version_no")},
            },
        ),
        migrations.CreateModel(
            name="SingleCifSpData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "last_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_modified_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "submit_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("submit_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "submit_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("submit_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "rejected_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rejected_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rejected_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rejected_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "discarded_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discarded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discarded_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("discarded_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "submit_status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "record_status",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "display_in_queue",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("queue_code", models.CharField(blank=True, max_length=25, null=True)),
                ("queue_name", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("common_data", models.TextField(blank=True, null=True)),
                ("additional_data", models.TextField(blank=True, null=True)),
                (
                    "primary_contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primary_email_address",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_representative_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cif", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "account_num1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_num2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("onboarding_channel", models.CharField(max_length=100)),
                (
                    "created_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "created_at_branch_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "application_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "application_branch_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "present_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "present_at_branch_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("role_code", models.CharField(blank=True, max_length=25, null=True)),
                ("product_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "kyc_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "file_upload_status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
            ],
            options={
                "db_table": "single_cif_sp_data",
                "managed": True,
                "unique_together": {
                    ("tenant", "internal_reference"),
                    ("tenant", "external_reference"),
                    ("tenant", "internal_reference", "version_no"),
                },
            },
        ),
        migrations.CreateModel(
            name="SingleCifRetailDataHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("archive_data", models.TextField(blank=True, null=True)),
                (
                    "archived_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "archived_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("archived_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "single_cif_retail_data_history",
                "managed": True,
                "unique_together": {("internal_reference", "version_no")},
            },
        ),
        migrations.CreateModel(
            name="SingleCifRetailData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                (
                    "internal_reference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("version_no", models.IntegerField(blank=True, null=True)),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "last_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_modified_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "submit_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("submit_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "submit_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("submit_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "rejected_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rejected_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rejected_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rejected_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "discarded_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discarded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discarded_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("discarded_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "submit_status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "application_status",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "display_in_queue",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("queue_code", models.CharField(blank=True, max_length=25, null=True)),
                ("queue_name", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("common_data", models.TextField(blank=True, null=True)),
                ("additional_data", models.TextField(blank=True, null=True)),
                (
                    "primary_contact_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "primary_email_address",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preferred_id_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_id_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cif", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "account_num1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_num2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("onboarding_channel", models.CharField(max_length=100)),
                (
                    "created_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "created_at_branch_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "application_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "application_branch_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "present_at_branch_code",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "present_at_branch_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("role_code", models.CharField(blank=True, max_length=25, null=True)),
                ("product_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "kyc_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "file_upload_status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
            ],
            options={
                "db_table": "single_cif_retail_data",
                "managed": True,
                "unique_together": {
                    ("tenant", "internal_reference"),
                    ("tenant", "external_reference"),
                    ("tenant", "internal_reference", "version_no"),
                },
            },
        ),
        migrations.CreateModel(
            name="RetailProductMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("product_key", models.CharField(max_length=50, unique=True)),
                ("product_name", models.CharField(max_length=50)),
                ("product_icon_path", models.TextField(blank=True, null=True)),
                (
                    "product_channel",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("scheme_description", models.TextField(blank=True, null=True)),
                ("documents_required", models.TextField(blank=True, null=True)),
                ("key_fact_path", models.TextField(blank=True, null=True)),
                (
                    "applicable_gender",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("scheme_code", models.CharField(max_length=50)),
                ("scheme_type", models.CharField(max_length=50)),
                ("gl_subhead_code", models.CharField(max_length=75)),
                (
                    "customer_nationality",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "account_currency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "annual_income",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "retail_account_category",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "retail_account_type",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("process_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "retail_product_mapping",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "product_key",
                        "product_name",
                        "product_channel",
                        "account_type",
                        "applicable_gender",
                        "scheme_code",
                        "scheme_type",
                        "gl_subhead_code",
                        "account_currency",
                        "annual_income",
                        "retail_account_category",
                        "retail_account_type",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="QueueConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("queue_code", models.CharField(max_length=100)),
                ("queue_name", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "queue_config",
                "managed": True,
                "unique_together": {
                    ("tenant", "queue_code", "queue_name"),
                    ("tenant", "queue_code"),
                },
            },
        ),
        migrations.CreateModel(
            name="ProcessTarget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("product_key", models.CharField(max_length=50)),
                ("target", models.CharField(max_length=50)),
                ("process_mode", models.CharField(max_length=50)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="onboarding.processmapping",
                    ),
                ),
            ],
            options={
                "db_table": "process_target",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OtpCounter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=254)),
                ("request_by_uuid", models.CharField(max_length=254)),
                ("request_by_username", models.CharField(max_length=254)),
                ("request_timestamp", models.CharField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("otp_request_id", models.CharField(max_length=254)),
                ("otp_expiry", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "otp_counter",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "request_by_uuid",
                        "request_by_username",
                        "request_timestamp",
                        "phone",
                        "otp_request_id",
                        "otp_expiry",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="KycMaster",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=100)),
                ("internal_reference", models.CharField(max_length=255)),
                ("kyc_number", models.CharField(max_length=255)),
                ("version_no", models.CharField(max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("primary_contact_number", models.CharField(max_length=100)),
                ("primary_email_address", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("additional_data", models.TextField(blank=True, null=True)),
                ("kyc_status", models.CharField(blank=True, max_length=50, null=True)),
                ("kyc_level", models.CharField(blank=True, max_length=100, null=True)),
                ("kyc_level_updated_at", models.DateTimeField(blank=True, null=True)),
                ("common_data", models.TextField(blank=True, null=True)),
                ("create_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data", models.TextField(blank=True, null=True)),
                (
                    "discarded_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discarded_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discarded_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("discarded_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "display_in_queue",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "last_action",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_perform_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_action_performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_action_performed_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_modified_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("queue_code", models.CharField(blank=True, max_length=25, null=True)),
                ("queue_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rejected_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rejected_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rejected_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rejected_timestamp", models.DateTimeField(blank=True, null=True)),
                ("submit_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "submit_by_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "submit_by_uuid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("submit_timestamp", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(max_length=100)),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("kyc_expires_at", models.DateTimeField(blank=True, null=True)),
                ("product_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "kyc_master",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "internal_reference",
                        "version_no",
                        "kyc_number",
                        "first_name",
                        "middle_name",
                        "last_name",
                        "primary_contact_number",
                        "primary_email_address",
                        "kyc_status",
                        "kyc_level",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="KycHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kyc_reference", models.CharField(max_length=100)),
                ("version_no", models.CharField(max_length=50)),
                ("archive_data", models.CharField(max_length=100)),
                ("archived_by_uuid", models.CharField(max_length=100)),
                ("archived_by", models.CharField(max_length=100)),
                ("archived_by_provider", models.CharField(max_length=100)),
                ("archived_timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "kyc_history",
                "managed": True,
                "unique_together": {
                    (
                        "kyc_reference",
                        "version_no",
                        "archive_data",
                        "archived_by_uuid",
                        "archived_by",
                        "archived_by_provider",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="KycDocuments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=100)),
                ("kyc_reference", models.CharField(max_length=255)),
                ("kyc_number", models.CharField(max_length=255)),
                ("version_no", models.CharField(max_length=50)),
                ("doc_type", models.CharField(max_length=255)),
                ("doc_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
            ],
            options={
                "db_table": "kyc_documents",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "kyc_reference",
                        "kyc_number",
                        "version_no",
                        "doc_type",
                        "doc_number",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="EtbProcessTarget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("actor", models.CharField(max_length=50)),
                ("process_mode", models.CharField(max_length=50)),
                ("product_category", models.CharField(max_length=50)),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="onboarding.processmapping",
                    ),
                ),
            ],
            options={
                "db_table": "etb_process_target",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BranchConfiguration",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("branch_code", models.CharField(max_length=50)),
                ("branch_type", models.CharField(max_length=50)),
                ("branch_name", models.CharField(max_length=255)),
                ("branch_details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "branch_configuration",
                "managed": True,
                "unique_together": {
                    ("tenant", "branch_code", "branch_type", "branch_name"),
                    ("tenant", "branch_code", "branch_type"),
                    ("tenant", "branch_code"),
                },
            },
        ),
        migrations.CreateModel(
            name="AgentRoleConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("agent_uuid", models.CharField(blank=True, max_length=255, null=True)),
                ("agent_name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=200)),
                ("role_name", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "agent_role_config",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "agent_uuid",
                        "agent_name",
                        "provider",
                        "role",
                        "role_name",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="AgentBranchConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("branch_code", models.CharField(max_length=50)),
                ("branch_type", models.CharField(max_length=50)),
                ("branch_name", models.CharField(max_length=255)),
                ("agent_uuid", models.CharField(blank=True, max_length=255, null=True)),
                ("agent_name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "agent_branch_config",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "agent_uuid",
                        "agent_name",
                        "provider",
                        "branch_code",
                        "branch_type",
                        "branch_name",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ActionConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("action_code", models.CharField(max_length=100)),
                ("action_name", models.CharField(max_length=254)),
            ],
            options={
                "db_table": "action_config",
                "managed": True,
                "unique_together": {
                    ("tenant", "action_code", "action_name"),
                    ("tenant", "action_code"),
                },
            },
        ),
        migrations.CreateModel(
            name="RoutingLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant", models.CharField(max_length=50)),
                ("route_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "from_branch_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "from_role_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "from_queue_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ac_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "to_branch_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "to_role_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "to_queue_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "increase_version",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "customer_type",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "condition_priority",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                ("call_cbs", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "route_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="onboarding.routingrules",
                    ),
                ),
            ],
            options={
                "db_table": "routing_log",
                "managed": True,
                "unique_together": {
                    (
                        "tenant",
                        "from_branch_code",
                        "from_role_code",
                        "from_queue_code",
                        "product",
                        "ac_code",
                        "to_branch_code",
                        "to_role_code",
                        "to_queue_code",
                        "route_condition",
                        "condition_priority",
                        "increase_version",
                        "customer_type",
                    )
                },
            },
        ),
    ]
